### ISSUE TITLE
Unable to resolve asset ID for "dart:core"

### ISSUE THREAD

**Issue by mohawkTrail** [angular/angular.dart.tutorial#142]
I cannot build the tutorial.  From Chapter01

Is it broke, or is it me?

pub get,....
[works]

pub build
Loading source assets... 
Loading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformers... 
Loading angular transformers... 
Building tutorial... 
[Error from InjectorGenerator on tutorial|web/main.dart]:
Unable to resolve asset ID for "dart:core"
Build error:
Transform InjectorGenerator on tutorial|web/main.dart threw error: <rethrow>
Caused by Could not resolve dart:core
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6762:7)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6727:7)
#2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2414:79)
#3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3046:17)
#4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3077:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1192:58)
#6      ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:157:25)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#8      ListIterable.toList (dart:_internal/iterable.dart:219)
#9      ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:158:10)
#10     _RootZone.runUnary (dart:async/zone.dart:1149)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#13     _Future._completeWithValue (dart:async/future_impl.dart:376)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

package:analyzer/src/generated/engine.dart 2115:11       AnalysisContextImpl.recordResolveDartLibraryTaskResults
package:analyzer/src/generated/engine.dart 5304:98       AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
package:analyzer/src/generated/engine.dart 14327:50      ResolveDartLibraryTask.accept
package:analyzer/src/generated/engine.dart 6732:12       AnalysisTask.perform
package:analyzer/src/generated/engine.dart 2414:79       AnalysisContextImpl._cacheDartResolutionData
package:analyzer/src/generated/engine.dart 3046:17       AnalysisContextImpl._getDartResolutionData
package:analyzer/src/generated/engine.dart 3077:14       AnalysisContextImpl._getDartResolutionData2
package:analyzer/src/generated/engine.dart 1192:58       AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25  ResolverImpl._performResolve.<fn>.<fn>
dart:_internal/iterable.dart 413                         MappedListIterable.elementAt
dart:_internal/iterable.dart 219                         ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10  ResolverImpl._performResolve.<fn>
dart:async/zone.dart 1149                                _RootZone.runUnary
dart:async/future_impl.dart 502                          _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 585                          _Future._propagateToListeners
dart:async/future_impl.dart 376                          _Future._completeWithValue
dart:async/future_impl.dart 430                          _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 43                    _microtaskLoop
dart:async/schedule_microtask.dart 52                    _microtaskLoopEntry
dart:isolate-patch/isolate_patch.dart 96                 _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 151                _RawReceivePortImpl._handleMessage

package:analyzer/src/generated/engine.dart 2115:11       AnalysisContextImpl.recordResolveDartLibraryTaskResults
package:analyzer/src/generated/engine.dart 5304:98       AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
package:analyzer/src/generated/engine.dart 14327:50      ResolveDartLibraryTask.accept
package:analyzer/src/generated/engine.dart 6732:12       AnalysisTask.perform
package:analyzer/src/generated/engine.dart 2414:79       AnalysisContextImpl._cacheDartResolutionData
package:analyzer/src/generated/engine.dart 3046:17       AnalysisContextImpl._getDartResolutionData
package:analyzer/src/generated/engine.dart 3077:14       AnalysisContextImpl._getDartResolutionData2
package:analyzer/src/generated/engine.dart 1192:58       AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25  ResolverImpl._performResolve.<fn>.<fn>
dart:_internal                                           ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10  ResolverImpl._performResolve.<fn>

Build failed.

**Comment by Moworld** [comment]
Dito

**Comment by kwalrath** [comment]
@pavelgj or @vicb any insight?

**Comment by mohawkTrail** [comment]
Someone suggested I go straight to Angular2.  Should we put up yellow tape and a "come back later" sign on this repository?

**Comment by kwalrath** [comment]
@naomiblack what do you think?

**Comment by df9ry** [comment]
Dito!

**Comment by kwalrath** [comment]
I tried to put up some tape, but had trouble building the site—a ruby problem iirc. Any help would be welcome.

**Comment by kwalrath** [comment]
Yes, please don't use angulardart.org. Just go to http://angular.io/dart and use Angular 2.

You're right that Dart Editor is discontinued. WebStorm is now the recommended IDE for web development with Dart, although other IDEs also work (e.g. Atom).

**Comment by figaw** [comment]
Okay, thank you!

I just wanted to try angular and dart together, and "angularDart" was the first thing that popped up.
